version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx
        volumes:
            - ./htdocs:/var/www/html
            - ./logs:/var/log/nginx
            - ./sites:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443